version: "3"
services:
  mongo:
    image: mongo
    networks:
      default:
        aliases:
          - mongo
  mongorestore:
    build: ./server/mongorestore
    depends_on:
      - mongo
  parse:
    image: yongjhih/parse-server
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      DATABASE_URI: mongodb://mongo/dev
      APP_ID: oss-f8-app-2017
      MASTER_KEY: oss-f8-app-2017-mk
    depends_on:
      - mongo
  parse_dashboard:
    build: ./server/parse-dashboard
    ports:
      - "4040:4040"
  graphql:
    build: ./server/graphql
    environment:
      - PARSE_URL=http://parse:1337/parse
    ports:
      - "4000:4000"
